### ISSUE TITLE
Have the option to include/exclude dropwizard metrics from WavefrontReporter

### ISSUE THREAD

**Issue by panghy** [wavefrontHQ/java#194]
The default configuration for dropwizard includes, among other things, jetty metrics which some customers do not find useful. We should have the factory allow (and remove by default perhaps) those metrics.

**Comment by panghy** [comment]
assigning to @vikramraman since you're on the agent side of things

**Comment by vikramraman** [comment]
Closing this as it has been moved into https://github.com/wavefrontHQ/wavefront-dropwizard-metrics-sdk-java.
