### ISSUE TITLE
MetricName class cannot be found

### ISSUE THREAD

**Issue by saravinth** [wavefrontHQ/java#217]
As per given in the documentation on https://github.com/wavefrontHQ/java/tree/master/dropwizard-metrics/4.0, The MetricName class cannot be resolved in the given maven dependency or the git given in  setting up the maven (git clone https://github.com/dropwizard/metrics.git, 
git clone https://github.com/wavefrontHQ/java.git).

**Comment by panghy** [comment]
This should now be fixed.
