### ISSUE TITLE
Can't find custom metrics on wavefront sent by wavefront client

### ISSUE THREAD

**Issue by jainbhargav** [wavefrontHQ/java#252]
I am able to send metrics from command prompt with nc -c command but while sending metrics with API, I could debug that API connects to server with isConnected() method of Wavefront class but can't locate metrics on wavefront sent by API using send function. I also got failure count as 0.

**Comment by basilisk487** [comment]
The client is using a buffered writer internally to reduce overhead, so once your batch of points is ready, call flush() method to make sure all the metrics are actually written to the TCP socket. Could you please try that and let us know if it works for you?

**Comment by jainbhargav** [comment]
I remember that I used to flush metrics once done with sending but that indeed work for me later. Our Wavefront server had some stringent requirement for accepting metrics with particular point tags. I can blame it but not sure. I can close this issue for now.

**Comment by jainbhargav** [comment]
Hello Vasily,

I wanted to contribute to WavefrontReporter in dropwizard-metrics
in wavefrontHQ Repository. What is the procedure for the same?

I also observed that there is no test classes written, is it fine to have
just checkin changes in WavefrontReporter class?

Regards,
Bhargav

**Comment by jainbhargav** [comment]
Hello Vasily,

I am trying to push my feature branch and always get *ERROR: Permission to
wavefrontHQ/java.git denied to jainbhargav.*
*fatal: Could not read from remote repository.*

*Please make sure you have the correct access rights*
*and the repository exists.*

I have checked and my remote are :

*origin ssh://git@github.com/wavefrontHQ/java.git
<http://git@github.com/wavefrontHQ/java.git> (fetch)*
*origin ssh://git@github.com/wavefrontHQ/java.git
<http://git@github.com/wavefrontHQ/java.git> (push)*

Can you please help me with this?

Regards,
Bhargav

**Comment by basilisk487** [comment]
@jainbhargav: That is correct - only team members have write access to wavefrontHQ/java. For submitting pull requests, you'll need to fork our repository first, instructions are available here:   https://guides.github.com/activities/forking/
