### ISSUE TITLE
Wavefront dropwizard metrics reporter for version 4.0.0

### ISSUE THREAD

**Issue by ankrim** [wavefrontHQ/java#281]
Hi,
Dropwizard metrics version 4.0.0 is released. can I use the wavefront reporter directly from Maven?

**Comment by panghy** [comment]
Just added support fro dropwizard metrics 4.0 (and removed support for the experimental dropwizard 4.0.x branch). Should be there once we make the next release.

**Comment by ankrim** [comment]
Thanks!

**Comment by ankrim** [comment]
Hi, I still can't find the new dropwizard-metrics-wavefront package as described in https://github.com/wavefrontHQ/java/tree/master/dropwizard-metrics/dropwizard-metrics-wavefront
Any idea when it will be available?

**Comment by vikramraman** [comment]
@ankrim It should be available within the next few weeks.

**Comment by vikramraman** [comment]
@ankrim FYI, the latest libs have been pushed to Maven repos. For dropwizard 4.0.0 you would want to use https://github.com/wavefrontHQ/java/tree/master/dropwizard-metrics/dropwizard-metrics

**Comment by ankrim** [comment]
Thanks, yes, I updated to the new release today.
