### ISSUE TITLE
WavefrontReporter supports additional point tags for specific metrics

### ISSUE THREAD

**Issue by curtis628** [wavefrontHQ/java#315]
Currently, the `WavefrontReporter` implementation allows me to include pointTags for all metrics that get exported to my Wavefront instance.

I'd like to add _additional_ point tags to specific metrics based off their name.

I'm interested in tracking response codes for a certain Health API. I might have the following `Meter` names in my `MetricRegistry` tracking the counts/rates of the various return codes for this health API:

* `health_api[status=200]`
* `health_api[status=500]`
* `health_api[status=503]`

Right now, the `WavefrontReporter` "sanitizes" a metric name like this. I'd like to see it be able to parse out key/value pairs within `[%s=%s]` and add them as additional point tags.

If they were point tags, I could create a Query for `ts(health_api)` and see a breakdown of all the different response codes. It would also roll up a "total" API calls metric automatically without me having to track it separately.

Is there a better way to accomplish this? Or is there a reason why this approach would be a bad idea? I'm admittedly no expert when it comes to Wavefront or Dropwizards.

**Comment by sushantdewan123** [comment]
Dropwizard5 RC2 already supports point tags but is not GA yet
https://github.com/dropwizard/metrics/releases/tag/v5.0.0-rc2

If you want you can use this reporter to accomplish this - 
https://github.com/wavefrontHQ/java/tree/master/dropwizard-metrics/dropwizard-metrics5

**Comment by curtis628** [comment]
@sushantdewan123 (or anyone from dropwizard really): I created a pull request that implements what I was looking for: https://github.com/wavefrontHQ/java/pull/318

I ended up doing my own work-around in my own code base which involved:
- copy/pasting existing `WavefrontReporter` implementation in my code base (had to do this due to `WavefrontReporter` having many fields `private`)
- made small changes that you can see if my pull request diff to enable per-metrics reporting

I hate copy/pasting... and figured if I needed it, perhaps someone else might? This is why I drafted the pull request. Please let me know what you think (and feel free to reject it if you don't think it will help other users :)

**Comment by curtis628** [comment]
> Dropwizard5 RC2 already supports point tags but is not GA yet
> https://github.com/dropwizard/metrics/releases/tag/v5.0.0-rc2
> 
> If you want you can use this reporter to accomplish this -
> https://github.com/wavefrontHQ/java/tree/master/dropwizard-metrics/dropwizard-metrics5

Also - I briefly looked into this, and it didn't solve my use case. That allows me to add custom point tags when I initially create the metric, but my use case involves supplying point tags at runtime; I don't know what point tags to use when I initially create the metric (because they are based on the runtime outcome of my API's logic).

Admittedly though, I didn't spend too much time investigating it because I need this for production use now, so I might've overlooked something.
