### ISSUE TITLE
Latest releases not showing up in OSS repositories

### ISSUE THREAD

**Issue by ddimensia** [wavefrontHQ/java#39]
I'm not seeing any releases since 3.10 in the OSS maven repositories.  It would be good if the recent releases could get published.

Also, it would be nice if the git repo is tagged per release so git history doesn't have to be used to determine what sha corresponds to a release.

**Comment by panghy** [comment]
Thanks ddimensia, I'll be uploading the artifacts to maven very soon

**Comment by panghy** [comment]
3.13 has been deployed into maven central
