### ISSUE TITLE
Push artifacts to PackageCloud within Docker

### ISSUE THREAD

**Issue by panghy** [wavefrontHQ/java#63]
https://packagecloud.io/docs#cli

package_cloud push wavefront/proxy-next/ubuntu/xenial wavefront-proxy_3.20-1_amd64.deb
package_cloud push wavefront/proxy-next/ubuntu/trusty wavefront-proxy_3.20-1_amd64.deb
package_cloud push wavefront/proxy-next/ubuntu/precise wavefront-proxy_3.20-1_amd64.deb
package_cloud push wavefront/proxy-next/debian/wheezy wavefront-proxy_3.20-1_amd64.deb
package_cloud push wavefront/proxy-next/debian/jessie wavefront-proxy_3.20-1_amd64.deb
package_cloud push wavefront/proxy-next/debian/buster wavefront-proxy_3.20-1_amd64.deb
package_cloud push wavefront/proxy-next/debian/stretch wavefront-proxy_3.20-1_amd64.deb

package_cloud push wavefront/proxy-next/el/6 wavefront-proxy-3.20-1.x86_64.rpm
package_cloud push wavefront/proxy-next/el/7 wavefront-proxy-3.20-1.x86_64.rpm

**Comment by moribellamy** [comment]
https://github.com/wavefrontHQ/java/commit/e6eadf07b5bbe42ad433e5dc861cea416c26ecde
